### ISSUE TITLE
Add documentation for the swift sdk and example iOS app

### ISSUE THREAD

**Issue by mplooster** [cobaltspeech/sdk-cubic#43]
Need to document
1. How to incorporate the swift sdk into new or existing projects (Either in the existing [installation.md](https://github.com/cobaltspeech/sdk-cubic/blob/master/docs-src/content/using-cubic-sdk/installation.md) file or if the instructions are too complicated, in a separate md file like android.md )

2. Add Swift code examples corresponding to the code samples for the other supported languages in [connecting.md](https://github.com/cobaltspeech/sdk-cubic/blob/master/docs-src/content/using-cubic-sdk/connecting.md), [recognize.md](https://github.com/cobaltspeech/sdk-cubic/blob/master/docs-src/content/using-cubic-sdk/recognize.md), and [streaming.md](https://github.com/cobaltspeech/sdk-cubic/blob/master/docs-src/content/using-cubic-sdk/streaming.md)

**Comment by renaissanceGeek** [comment]
I understand that writing documentation in English is a challenge, so don't worry about making it sound good. If you just do a first rough draft to get the information in place, I'll revise it to be more user friendly.
