### ISSUE TITLE
newclient: block for connection to be established

### ISSUE THREAD

**Issue by happyalu** [cobaltspeech/sdk-cubic#46]
SDK functions such as [this in go](https://github.com/cobaltspeech/sdk-cubic/blob/master/grpc/go-cubic/client.go#L48) do not block until the underlying grpc connection is established; thus even if the wrong URL or security mechanism is used, the client creation appears to succeed when it doesn't. Explore the use of the WithBlock() dial option in grpc. Verify that it doesn't adversely impact anything else.

**Comment by mplooster** [comment]
I've noticed this before as well. If the `WithBlock()` dial option turns out to work well, we may want to update our other SDKs to use it as well.
