### ISSUE TITLE
grpc-cpp: sdk docs

### ISSUE THREAD

**Issue by happyalu** [cobaltspeech/sdk-cubic#58]
Should the sdk-docs include instructions and examples for the C++ client?

**Comment by mplooster** [comment]
I don't know that the webdocs for the SDK should have those instructions, but there should at least be a README. 

If we move examples to their own repository, I think it would be less distracting to have webdocs for them there, but in this repo I think adding instructions for the examples in the webdocs would distract from the main purpose of the docs, which is to be a guide and reference for the SDK itself.

**Comment by happyalu** [comment]
I think my question was: [this](https://cobaltspeech.github.io/sdk-cubic/using-cubic-sdk/recognize/) has four languages, but not C++. is that something we need/want, or skipped on purpose?

**Comment by mplooster** [comment]
We need it, as noted in issue #32.

**Comment by happyalu** [comment]
Ok, closing this as duplicate of #32
