### ISSUE TITLE
examples: relocate config.toml?

### ISSUE THREAD

**Issue by happyalu** [cobaltspeech/sdk-cubic#62]
Should `examples/config.sample.toml` be part of the C++ example, rather than at the top level?

**Comment by mplooster** [comment]
It was put at the top level so that it could be shared among the demos for different languages.

**Comment by happyalu** [comment]
Ok. I'm not sure it is being reused, but would you recommend we leave it as it is for now?

**Comment by mplooster** [comment]
Either way. It would have been reused if I had managed to get to the python and go examples :grin:. I don't mind if we put it in the C++ dir until then.

**Comment by happyalu** [comment]
Let's do this along with what we decide for examples. Moving it out of v1.4.0 milestone.

**Comment by mplooster** [comment]
The examples folder has been removed from this repo, so this is no longer an issue.
