### ISSUE TITLE
move examples to separate repos?

### ISSUE THREAD

**Issue by happyalu** [cobaltspeech/sdk-cubic#64]
Would it make sense to move example code in here to respective repositories for each language? It would simplify the versioning of this repo and allow more flexibility in making changes to the examples.  The cubic-cli repo could be thought of as the go example repo.

**Comment by mplooster** [comment]
To give my two cents...as examples are becoming larger, I am in favor of this change. Although, to reduce the number of repos we have to maintain, I would also advocate that each language-specific repo have examples for all of our SDKs, not just sdk-cubic. This would also allow us to reuse some code between examples (like audio I/O). I would also be OK with it if we want to have a single examples repo, where the top-level directories in it are language specific.

**Comment by happyalu** [comment]
One advantage of the examples being a separate repo is that they can act as external tests (with CI) to the actual SDK that is in this repo. I worry that at the moment there's not an easy way to assert a clean boundary between the sdk and the example especially as our examples grow larger.

**Comment by jhollowayj** [comment]
I assume we would just add links to the different example's in this repos top level readme?

**Comment by happyalu** [comment]
Or from the docs.

**Comment by mplooster** [comment]
I have no problem adding links to the docs.

**Comment by renaissanceGeek** [comment]
I created the repos--private for now since they're empty, but we can make them public once we've moved the examples out of this repo into them.
* https://github.com/cobaltspeech/examples-cpp
* https://github.com/cobaltspeech/examples-ios
* https://github.com/cobaltspeech/examples-android
* https://github.com/cobaltspeech/examples-csharp
